# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 15e83c8
_src_path: https://github.com/slaclab/eed-java-backend-template.git
github_owner: eed-web-application
project_name: code-inventory-system
project_slug: code_inventory_system
