name: BuildAndTest
on: 
    push:
        branches:
        - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
    build:
        uses: eed-web-application/core-inventory-system-deployment/.github/workflows/build-test-create.yml@main
        secrets: inherit

